<?php
return [
    'GET' => [
        '/' => ['uses' => 'HomeController@index', 'name' => 'home'],
        '/store' => ['uses' => 'StoreController@home', 'name' => 'store.home'],
        '/kategori/{slug}' => ['uses' => 'StoreController@category', 'name' => 'store.category'],
        '/urun/{slug}' => ['uses' => 'StoreController@product', 'name' => 'store.product'],
        '/arama' => ['uses' => 'StoreController@search', 'name' => 'store.search'],
        '/login' => ['uses' => 'AuthController@showLoginForm', 'name' => 'login'],
        '/register' => ['uses' => 'AuthController@showRegisterForm', 'name' => 'register'],
        '/password/forgot' => ['uses' => 'AuthController@showForgotPasswordForm', 'name' => 'password.forgot'],
        '/password/reset' => ['uses' => 'AuthController@showResetForm', 'name' => 'password.reset'],
        '/logout' => ['uses' => 'AuthController@logout', 'middleware' => ['auth'], 'name' => 'logout'],
        '/account' => ['uses' => 'AccountController@index', 'middleware' => ['auth'], 'name' => 'account'],
        '/account/security' => ['uses' => 'AccountController@security', 'middleware' => ['auth'], 'name' => 'account.security'],
        '/admin' => ['uses' => 'Admin\\DashboardController@index', 'middleware' => ['auth', 'role:admin'], 'name' => 'admin.dashboard'],
        '/admin/orders' => ['uses' => 'Admin\\OrdersController@index', 'middleware' => ['auth', 'role:admin'], 'name' => 'admin.orders.index'],
        '/admin/orders/{reference}' => ['uses' => 'Admin\\OrdersController@show', 'middleware' => ['auth', 'role:admin'], 'name' => 'admin.orders.show'],
        '/admin/products' => ['uses' => 'Admin\\ProductsController@index', 'middleware' => ['auth', 'role:admin'], 'name' => 'admin.products.index'],
        '/cart' => ['uses' => 'CartController@show', 'name' => 'cart.view'],
        '/checkout' => ['uses' => 'CheckoutController@show', 'name' => 'checkout.show'],
        '/order/{reference}/confirmation' => ['uses' => 'OrderController@confirmation', 'name' => 'order.confirmation'],
        '/order/{reference}/codes' => ['uses' => 'OrderController@codes', 'middleware' => ['auth'], 'name' => 'order.codes'],
        '/order/{reference}/status' => ['uses' => 'OrderController@updateStatus', 'name' => 'order.status'],
        '/sitemap.xml' => ['uses' => 'SeoController@sitemap', 'name' => 'seo.sitemap'],
        '/robots.txt' => ['uses' => 'SeoController@robots', 'name' => 'seo.robots'],
    ],
    'POST' => [
        '/login' => ['uses' => 'AuthController@login', 'name' => 'login.submit'],
        '/register' => ['uses' => 'AuthController@register', 'name' => 'register.submit'],
        '/password/forgot' => ['uses' => 'AuthController@sendResetLink', 'name' => 'password.email'],
        '/password/reset' => ['uses' => 'AuthController@resetPassword', 'name' => 'password.update'],
        '/cart/add' => ['uses' => 'CartController@add', 'name' => 'cart.add'],
        '/cart/update' => ['uses' => 'CartController@update', 'name' => 'cart.update'],
        '/cart/remove' => ['uses' => 'CartController@remove', 'name' => 'cart.remove'],
        '/checkout' => ['uses' => 'CheckoutController@process', 'name' => 'checkout.process'],
        '/account/two-factor/begin' => ['uses' => 'AccountController@beginTwoFactor', 'middleware' => ['auth'], 'name' => 'account.security.begin'],
        '/account/two-factor/confirm' => ['uses' => 'AccountController@confirmTwoFactor', 'middleware' => ['auth'], 'name' => 'account.security.confirm'],
        '/account/two-factor/disable' => ['uses' => 'AccountController@disableTwoFactor', 'middleware' => ['auth'], 'name' => 'account.security.disable'],
        '/order/{reference}/codes/reveal' => ['uses' => 'OrderController@revealCodes', 'middleware' => ['auth'], 'name' => 'order.codes.reveal'],
        '/order/{reference}/refund' => ['uses' => 'OrderController@refund', 'middleware' => ['auth'], 'name' => 'order.refund'],
        '/webhook/paytr' => ['uses' => 'WebhookController@paytr', 'name' => 'webhook.paytr'],
        '/webhook/iyzico' => ['uses' => 'WebhookController@iyzico', 'name' => 'webhook.iyzico'],
        '/webhook/param' => ['uses' => 'WebhookController@param', 'name' => 'webhook.param'],
        '/webhook/papara' => ['uses' => 'WebhookController@papara', 'name' => 'webhook.papara'],
        '/webhook/havale' => ['uses' => 'WebhookController@bankTransfer', 'name' => 'webhook.bank'],
        '/admin/orders/{reference}/resend' => ['uses' => 'Admin\\OrdersController@resend', 'middleware' => ['auth', 'role:admin'], 'name' => 'admin.orders.resend'],
        '/admin/orders/{reference}/topup' => ['uses' => 'Admin\\OrdersController@finalizeTopup', 'middleware' => ['auth', 'role:admin'], 'name' => 'admin.orders.topup'],
        '/admin/products' => ['uses' => 'Admin\\ProductsController@store', 'middleware' => ['auth', 'role:admin'], 'name' => 'admin.products.store'],
    ],
];
